---
- name: Ensure 'users' group exists with GID 100
  group:
    name: users
    gid: 100
    state: present

- name: Add 'victoriametrics' user to 'users' group
  user:
    name: victoriametrics
    groups: users
    append: yes

- name: Ensure the directory for VictoriaMetrics data exists on NAS
  file:
    path: "{{ victoria_metrics_dir }}"
    state: directory
    owner: nick              # owner matching Unraid (uid 1000)
    group: users             # group matching Unraid (gid 100)
    mode: '0775'

- name: Ensure correct ownership of the NFS mount directory (with become)
  file:
    path: "{{ victoria_metrics_dir }}"
    owner: victoriametrics
    group: victoriametrics
    recurse: yes

- name: Fix NFS share permissions if needed (temporary fix for UID/GID issues)
  command: chown -R victoriametrics:victoriametrics {{ victoria_metrics_dir }}
  become: yes
  when: ansible_facts['os_family'] == "Debian"  # Check if it's an Ubuntu-based system

- name: Copy the systemd service file for VictoriaMetrics
  copy:
    src: victoriametrics.service  # This is now in the 'files' directory
    dest: /etc/systemd/system/victoriametrics.service
    mode: '0644'  # You can set permissions now, as the file is copied from 'files'

- name: Reload systemd to register the new service
  systemd:
    daemon_reload: yes

- name: Enable and start VictoriaMetrics service
  systemd:
    name: victoriametrics
    state: started
    enabled: yes
