---
- name: Ensure 'users' group exists with GID 100 (matches Unraid NAS)
  group:
    name: users
    gid: 100
    state: present

- name: Add 'victoriametrics' user to 'users' group for NAS access
  user:
    name: victoriametrics
    groups: users
    append: yes

# IMPORTANT: Permissions and ownership on /mnt/nas/victoriametrics must be set directly on Unraid.
# Ansible cannot change ownership or permissions of NAS-mounted directories remotely.
# Ensure manually on Unraid (one-time setup):
# mkdir -p /mnt/user/victoriametrics
# chown nick:users /mnt/user/victoriametrics
# chmod 775 /mnt/user/victoriametrics

- name: Ensure the directory for VictoriaMetrics data exists (NAS-mounted)
  file:
    path: "{{ victoria_metrics_dir }}"
    state: directory
  become: false  # Prevent permission/ownership modifications (not permitted on NAS mounts)

- name: Copy the systemd service file for VictoriaMetrics
  copy:
    src: victoriametrics.service.j2
    dest: /etc/systemd/system/victoriametrics.service
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start VictoriaMetrics service
  systemd:
    name: victoriametrics
    state: started
    enabled: yes
