---
# IMPORTANT: Permissions and ownership on /mnt/nas/victoriametrics must be set directly on Unraid.
# Ansible cannot change ownership or permissions of NAS-mounted directories remotely.
# Ensure manually on Unraid (one-time setup):
# mkdir -p /mnt/user/victoriametrics
# chown nick:users /mnt/user/victoriametrics
# chmod 775 /mnt/user/victoriametrics


- name: Copy the systemd service file for VictoriaMetrics
  template:
    src: victoriametrics.service.j2
    dest: /etc/systemd/system/victoriametrics.service
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start VictoriaMetrics service
  systemd:
    name: victoriametrics
    state: started
    enabled: yes

- name: Verify VictoriaMetrics is running
  uri:
    url: http://localhost:8428/health
    return_content: yes
  register: health_check
  failed_when: "'OK' not in health_check.content"
  retries: 3
  delay: 10