---
- name: Install and configure VictoriaMetrics on Ubuntu 22.04
  hosts: victoriametrics  # Replace with your VM hostname or IP address
  become: yes
  become_method: sudo  # Explicitly set sudo
  become_user: root  # Run as root
  vars:
    # Define NFS mount details for the Unraid NAS
    nas_mount_point: "/mnt/nas"
    nas_server: "{{ nas_ip }}"  # Replace with your NAS IP or hostname
    nas_share: "/mnt/user/victoriametrics-{{ env | default('dev') }}"  # Replace with your updated NFS share path on Unraid
    victoria_metrics_dir: "/mnt/nas/victoriametrics"
    victoria_metrics_bin: "/usr/local/bin/victoria-metrics-prod"
    victoria_metrics_version: "v1.114.0"  # Replace with the desired version of VictoriaMetrics

  roles:
    - nfs_mount
    - victoriametrics_user
    - victoriametrics_install
    - victoriametrics_service
