---
- name: Install dependencies
  apt:
    name:
      - curl
      - tar
      - wget
      - gnupg
    state: present
    update_cache: yes

- name: Download VictoriaMetrics binary
  get_url:
    url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoria_metrics_version }}/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz"
    dest: "/tmp/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz"
    mode: '0644'
  register: download_result

- name: Extract VictoriaMetrics tarball
  ansible.builtin.unarchive:
    src: "/tmp/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
  register: extract_result

- name: Copy VictoriaMetrics binary to bin directory
  ansible.builtin.copy:
    src: "/tmp/victoria-metrics-prod"
    dest: "/usr/local/bin/victoria-metrics-prod"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz"
    - "/tmp/victoria-metrics-prod"

- name: Set permissions for VictoriaMetrics binary
  file:
    path: /usr/local/bin/victoria-metrics-prod
    owner: root
    group: root
    mode: '0755'
