---
- name: Install dependencies
  apt:
    name:
      - curl
      - tar
      - wget
      - gnupg
    state: present
    update_cache: yes

- name: Download VictoriaMetrics binary
  shell: |
    wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoria_metrics_version }}/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz
    tar -xvzf victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz
    mv victoria-metrics-linux-amd64-{{ victoria_metrics_version }}/victoria-metrics /usr/local/bin/victoriametrics
    rm -rf victoria-metrics-linux-amd64-{{ victoria_metrics_version }}*
  args:
    creates: /usr/local/bin/victoriametrics  # Ensure that this task only runs if the binary doesn't already exist

- name: Debug to check if VictoriaMetrics binary exists
  stat:
    path: /usr/local/bin/victoriametrics
  register: vm_binary

- name: Show the status of the VictoriaMetrics binary
  debug:
    var: vm_binary

- name: Set permissions for VictoriaMetrics binary
  file:
    path: /usr/local/bin/victoriametrics
    owner: root
    group: root
    mode: '0755'
  when: vm_binary.stat.exists  # Only set permissions if the file exists
