---
- name: Install dependencies
  apt:
    name:
      - curl
      - tar
      - wget
      - gnupg
    state: present
    update_cache: yes

- name: Download VictoriaMetrics binary
  shell: |
    wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoria_metrics_version }}/victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz
    tar -xvzf victoria-metrics-linux-amd64-{{ victoria_metrics_version }}.tar.gz
    mv victoria-metrics-linux-amd64-{{ victoria_metrics_version }}/victoria-metrics-prod /usr/local/bin/victoria-metrics-prod
    rm -rf victoria-metrics-linux-amd64-{{ victoria_metrics_version }}*

- name: Debug to list all files in the current directory
  shell: ls -l
  register: extracted_files
  changed_when: false

- name: Show the list of extracted files
  debug:
    var: extracted_files.stdout


- name: Debug to check if VictoriaMetrics binary exists
  stat:
    path: /usr/local/bin/victoriametrics
  register: vm_binary

- name: Show the status of the VictoriaMetrics binary
  debug:
    var: vm_binary

- name: Set permissions for VictoriaMetrics binary
  file:
    path: /usr/local/bin/victoriametrics
    owner: root
    group: root
    mode: '0755'
  when: vm_binary.stat.exists  # Only set permissions if the file exists
