---
- name: Ensure nfs-common package is installed
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Ensure required directories exist
  file:
    path: "{{ nas_mount_point }}"
    state: directory
    mode: '0755'

- name: Debug NFS variables
  debug:
    msg: 
      - "NAS Server: {{ nas_server }}"
      - "NAS Share: {{ nas_share }}"
      - "Mount Point: {{ nas_mount_point }}"
      - "Environment: {{ env | default('dev') }}"

- name: Check NFS exports on server
  shell: "showmount -e {{ nas_server }}"
  register: showmount_result
  ignore_errors: yes
  changed_when: false

- name: Display available NFS exports
  debug:
    var: showmount_result.stdout_lines

- name: Check if mount point is already mounted
  shell: "mount | grep {{ nas_mount_point }}"
  register: mount_check
  changed_when: false
  failed_when: false

- name: Find processes using the mount point
  shell: "lsof {{ nas_mount_point }} 2>/dev/null || echo 'No processes using mount'"
  register: lsof_result
  changed_when: false
  failed_when: false
  when: mount_check.rc == 0

- name: Display processes using the mount point
  debug:
    var: lsof_result.stdout_lines
  when: mount_check.rc == 0

- name: Attempt lazy unmount (detach immediately)
  command: "umount -l {{ nas_mount_point }}"
  ignore_errors: yes
  changed_when: false
  when: mount_check.rc == 0

- name: Mount the NFS share from Unraid NAS
  mount:
    path: "{{ nas_mount_point }}"
    src: "{{ nas_server }}:{{ nas_share }}"
    fstype: nfs
    opts: "rw,soft,intr,nfsvers=4"
    state: mounted

- name: Check if mount was successful
  shell: "mount | grep {{ nas_mount_point }}"
  register: mount_result
  changed_when: false
  failed_when: false
  
- name: Display mount details
  debug:
    var: mount_result.stdout_lines
  when: mount_result.rc == 0

- name: Fail if mount was unsuccessful
  fail:
    msg: "NFS mount failed. Please check your NAS server and share path."
  when: mount_result.rc != 0

- name: Ensure the directory for VictoriaMetrics data exists (NAS-mounted)
  file:
    path: "{{ victoria_metrics_dir }}"
    state: directory
    mode: '0755'
    owner: victoriametrics
    group: victoriametrics
  become: true
